"""
Grad-CAM visualization for ResNet-152V2 chest X-ray pneumonia classifier.
Uses keras 3 with PyTorch backend (no TensorFlow required).

Runs on three image sets:
  - clean     : adult test images (baseline)
  - fgsm      : FGSM-attacked images
  - pediatric : Pool B domain-shift images

Outputs 3-panel figures (original | heatmap | overlay) to gradcam_outputs/.
Title question: is the model attending to lung opacity or bone density?
"""

import os
os.environ["KERAS_BACKEND"] = "torch"

import glob
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import cv2
import torch
import keras

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
MODEL_PATH    = "baseline_resnet152v2.keras"
CLEAN_DIR     = "chest_xray/test"
FGSM_DIR      = "fgsm_outputs"          # generated by fgsm_export.py
PEDIATRIC_DIR = "pool_b/Master_Dataset/test"

TARGET_LAYER  = "conv5_block3_out"
IMG_SIZE      = (224, 224)
N_SAMPLES     = 10
CLASS_NAMES   = ["NORMAL", "PNEUMONIA"]

IMAGENET_MEAN = np.array([0.485, 0.456, 0.406], dtype=np.float32)
IMAGENET_STD  = np.array([0.229, 0.224, 0.225], dtype=np.float32)

# ---------------------------------------------------------------------------
# Preprocessing
# ---------------------------------------------------------------------------

def preprocess(img_path: str) -> tuple[np.ndarray, np.ndarray]:
    """Return (input_array [1,224,224,3] float32, display_rgb [224,224,3] uint8)."""
    img_bgr = cv2.imread(img_path)
    if img_bgr is None:
        raise FileNotFoundError(f"Cannot read image: {img_path}")
    img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
    img_resized = cv2.resize(img_rgb, IMG_SIZE)
    display = img_resized.copy()
    x = img_resized.astype(np.float32) / 255.0
    x = (x - IMAGENET_MEAN) / IMAGENET_STD
    return np.expand_dims(x, 0), display   # [1, H, W, C]


# ---------------------------------------------------------------------------
# Layer lookup (searches nested sub-models)
# ---------------------------------------------------------------------------

def find_layer(model: keras.Model, name: str):
    """Recursively search for a layer by name through nested models."""
    for layer in model.layers:
        if layer.name == name:
            return layer
        if hasattr(layer, "layers"):
            found = find_layer(layer, name)
            if found is not None:
                return found
    return None


# ---------------------------------------------------------------------------
# Grad-CAM (PyTorch hooks + autograd)
# ---------------------------------------------------------------------------

def make_gradcam_heatmap(
    img_array: np.ndarray,
    model: keras.Model,
    last_conv_layer_name: str,
) -> np.ndarray:
    """
    Compute Grad-CAM heatmap w.r.t. the predicted class.
    Uses PyTorch forward/backward hooks on the target keras layer.
    Returns float32 array in [0, 1] of shape (H, W).
    """
    target_layer = find_layer(model, last_conv_layer_name)

    activations = [None]
    gradients   = [None]

    def fwd_hook(module, inp, out):
        activations[0] = out

    def bwd_hook(module, grad_in, grad_out):
        gradients[0] = grad_out[0]

    h_fwd = target_layer.register_forward_hook(fwd_hook)
    h_bwd = target_layer.register_full_backward_hook(bwd_hook)

    # Convert to torch tensor — keras torch backend accepts numpy or torch
    x = torch.tensor(img_array, dtype=torch.float32)

    # Forward
    preds = model(x)   # torch tensor with torch backend

    # Score for predicted class
    if preds.shape[-1] == 1:
        score = preds[0, 0]
    else:
        score = preds[0, int(preds[0].argmax())]

    # Backward
    model.zero_grad()
    score.backward()

    h_fwd.remove()
    h_bwd.remove()

    act  = activations[0].detach().cpu()   # conv feature maps
    grad = gradients[0].detach().cpu()     # gradients same shape

    # Support both NHWC [N,H,W,C] and NCHW [N,C,H,W]
    if act.ndim == 4:
        if act.shape[1] == act.shape[2] or act.shape[-1] > act.shape[1]:
            # NHWC: pool over H,W (dims 1,2)
            weights = grad[0].mean(dim=(0, 1))          # [C]
            heatmap = (act[0] * weights).sum(dim=-1)    # [H, W]
        else:
            # NCHW: pool over H,W (dims 2,3)
            weights = grad[0].mean(dim=(1, 2))          # [C]
            heatmap = (act[0] * weights[:, None, None]).sum(dim=0)  # [H, W]
    else:
        raise ValueError(f"Unexpected activation shape: {act.shape}")

    heatmap = torch.relu(heatmap).numpy()
    if heatmap.max() > 0:
        heatmap /= heatmap.max()
    return heatmap.astype(np.float32)


# ---------------------------------------------------------------------------
# Overlay
# ---------------------------------------------------------------------------

def overlay_heatmap(
    heatmap: np.ndarray,
    original: np.ndarray,
    alpha: float = 0.45,
) -> tuple[np.ndarray, np.ndarray]:
    h, w = original.shape[:2]
    heatmap_uint8 = np.uint8(255 * heatmap)
    heatmap_resized = cv2.resize(heatmap_uint8, (w, h))
    coloured_bgr = cv2.applyColorMap(heatmap_resized, cv2.COLORMAP_JET)
    coloured_rgb = cv2.cvtColor(coloured_bgr, cv2.COLOR_BGR2RGB)
    overlay = cv2.addWeighted(
        cv2.cvtColor(original, cv2.COLOR_RGB2BGR), 1 - alpha,
        coloured_bgr, alpha, 0,
    )
    overlay_rgb = cv2.cvtColor(overlay, cv2.COLOR_BGR2RGB)
    return coloured_rgb, overlay_rgb


# ---------------------------------------------------------------------------
# Figure
# ---------------------------------------------------------------------------

def save_figure(
    original, heatmap_rgb, overlay_rgb,
    out_path, title, pred_label, confidence,
) -> None:
    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    fig.suptitle(
        f"{title}\nPred: {pred_label}  ({confidence:.1%}) | "
        "Attending to: lung opacity or bone density?",
        fontsize=11, fontweight="bold",
    )
    axes[0].imshow(original);     axes[0].set_title("Original");          axes[0].axis("off")
    axes[1].imshow(heatmap_rgb);  axes[1].set_title("Grad-CAM Heatmap"); axes[1].axis("off")
    axes[2].imshow(overlay_rgb);  axes[2].set_title("Overlay (α=0.45)"); axes[2].axis("off")

    sm = plt.cm.ScalarMappable(cmap="jet", norm=plt.Normalize(0, 1))
    sm.set_array([])
    plt.colorbar(sm, ax=axes[1], fraction=0.046, pad=0.04)

    plt.tight_layout()
    plt.savefig(out_path, dpi=150, bbox_inches="tight")
    plt.close(fig)


# ---------------------------------------------------------------------------
# Per-set processing
# ---------------------------------------------------------------------------

def collect_image_paths(directory: str, n: int) -> list[str]:
    exts = ("*.jpg", "*.jpeg", "*.png", "*.bmp")
    paths = []
    for ext in exts:
        paths.extend(glob.glob(os.path.join(directory, "**", ext), recursive=True))
        paths.extend(glob.glob(os.path.join(directory, ext)))
    return sorted(set(paths))[:n]


def run_set(model, directory, tag, out_dir) -> None:
    set_out = os.path.join(out_dir, tag)
    os.makedirs(set_out, exist_ok=True)

    img_paths = collect_image_paths(directory, N_SAMPLES)
    if not img_paths:
        print(f"[{tag}] WARNING: no images found in {directory!r}, skipping.")
        return

    print(f"\n[{tag}] Processing {len(img_paths)} images from {directory!r}")

    for i, img_path in enumerate(img_paths):
        try:
            img_array, display = preprocess(img_path)
        except FileNotFoundError as e:
            print(f"  [{i+1}] SKIP — {e}")
            continue

        # Prediction
        with torch.no_grad():
            preds = model(torch.tensor(img_array, dtype=torch.float32))
        preds_np = preds.cpu().numpy() if hasattr(preds, "numpy") else np.array(preds)

        if preds_np.shape[-1] == 1:
            prob = float(preds_np[0, 0])
            pred_idx = int(prob >= 0.5)
            confidence = prob if pred_idx == 1 else 1 - prob
        else:
            pred_idx = int(np.argmax(preds_np[0]))
            confidence = float(preds_np[0, pred_idx])

        pred_label = CLASS_NAMES[pred_idx]

        heatmap = make_gradcam_heatmap(img_array, model, TARGET_LAYER)
        heatmap_rgb, overlay_rgb = overlay_heatmap(heatmap, display)

        fname    = os.path.splitext(os.path.basename(img_path))[0]
        out_path = os.path.join(set_out, f"{fname}_gradcam.png")
        title    = f"[{tag.upper()}] {fname} — ResNet-152V2 | layer: {TARGET_LAYER}"
        save_figure(display, heatmap_rgb, overlay_rgb, out_path, title, pred_label, confidence)

        print(f"  [{i+1}/{len(img_paths)}] {fname} → {pred_label} ({confidence:.1%})  saved: {out_path}")

    print(f"[{tag}] Done. Figures in {set_out!r}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    os.makedirs("gradcam_outputs", exist_ok=True)

    print(f"Loading model from {MODEL_PATH!r} (keras backend: {os.environ['KERAS_BACKEND']}) ...")
    model = keras.models.load_model(MODEL_PATH)

    target_layer = find_layer(model, TARGET_LAYER)
    if target_layer is None:
        raise ValueError(f"Layer {TARGET_LAYER!r} not found anywhere in the model.")
    print(f"Target layer confirmed: {TARGET_LAYER!r}")

    for directory, tag in [
        (CLEAN_DIR,     "clean"),
        (FGSM_DIR,      "fgsm"),
        (PEDIATRIC_DIR, "pediatric"),
    ]:
        run_set(model, directory, tag, "gradcam_outputs")

    print("\nAll outputs saved to gradcam_outputs/")


if __name__ == "__main__":
    main()
